# Linear Algebra for Machine Learning (Part 1)

## Introduction

Linear Algebra is the mathematical foundation of Machine Learning. Almost every ML algorithm represents data as vectors and matrices and performs mathematical operations on them.

It is widely used in:

- Linear Regression
- Logistic Regression
- Neural Networks
- PCA
- Recommendation Systems
- Computer Vision
- Natural Language Processing

---

# Why Linear Algebra?

Machine Learning models cannot understand tables or text directly. They convert everything into numbers.

Example:

| Age | Salary |
|------|---------|
|20|25000|
|25|35000|
|30|50000|

becomes

\[
X=
\begin{bmatrix}
20 & 25000\\
25 & 35000\\
30 & 50000
\end{bmatrix}
\]

Every ML algorithm performs operations on this matrix.

---

# Scalars

## Definition

A scalar is a single numerical value.

Examples:

- Age = 20
- Salary = 50000
- Learning Rate = 0.01
- Bias = 2

---

## Mathematical Representation

\[
a=5
\]

where

- \(a\) = Scalar

---

## Mathematical Intuition

A scalar has only magnitude.

It has:

- No direction
- No dimensions

Example:

Temperature = **35°C**

It represents only one value.

---

## ML Applications

- Learning Rate
- Bias
- Loss Value
- Accuracy
- Regularization Parameter

---

# Vectors

## Definition

A vector is an ordered collection of numbers.

It represents one data point or one feature.

---

## Mathematical Representation

Column Vector

\[
x=
\begin{bmatrix}
2\\
4\\
6
\end{bmatrix}
\]

Row Vector

\[
x=
\begin{bmatrix}
2&4&6
\end{bmatrix}
\]

---

## Mathematical Intuition

A vector has:

- Magnitude
- Direction

Unlike a scalar, it can represent movement or position.

Example:

A person's information

| Feature | Value |
|----------|-------|
|Age|20|
|Height|170|
|Weight|65|

Vector

\[
x=
\begin{bmatrix}
20\\
170\\
65
\end{bmatrix}
\]

---

## Vector Magnitude

The length (norm) of a vector is

\[
||x||=\sqrt{x_1^2+x_2^2+\cdots+x_n^2}
\]

Example

\[
x=
\begin{bmatrix}
3\\
4
\end{bmatrix}
\]

\[
||x||=\sqrt{3^2+4^2}=5
\]

---

## ML Applications

- Feature Vector
- Word Embeddings
- Image Pixels
- TF-IDF Vectors

---

# Matrices

## Definition

A matrix is a collection of vectors arranged in rows and columns.

It usually represents an entire dataset.

---

## Mathematical Representation

\[
A=
\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}
\]

---

## Shape of Matrix

For

\[
A_{m\times n}
\]

- \(m\) = Number of rows
- \(n\) = Number of columns

Example

\[
3\times2
\]

means

- 3 rows
- 2 columns

---

## Mathematical Intuition

Rows represent observations.

Columns represent features.

Example

|Age|Height|Weight|
|---|------|------|
|20|170|65|
|22|175|70|
|25|180|75|

becomes

\[
X=
\begin{bmatrix}
20&170&65\\
22&175&70\\
25&180&75
\end{bmatrix}
\]

---

## ML Applications

- Dataset Representation
- Weight Matrix
- Confusion Matrix
- Covariance Matrix

---

# Matrix Multiplication

## Definition

Matrix multiplication combines two matrices to produce a new transformed matrix.

---

## Mathematical Rule

If

\[
A_{m\times n}
\]

and

\[
B_{n\times p}
\]

then

\[
AB=C_{m\times p}
\]

The inner dimensions must be equal.

---

## Formula

Each element is computed as

\[
c_{ij}=\sum_{k=1}^{n}a_{ik}b_{kj}
\]

---

## Example

\[
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
\]

\[
B=
\begin{bmatrix}
5&6\\
7&8
\end{bmatrix}
\]

Result

\[
AB=
\begin{bmatrix}
19&22\\
43&50
\end{bmatrix}
\]

---

## Mathematical Intuition

A matrix represents a transformation.

Matrix multiplication applies that transformation to another matrix or vector.

It can:

- Rotate
- Scale
- Translate
- Transform

the data.

---

## ML Intuition

Every Dense Layer in a Neural Network computes

\[
Y=WX+b
\]

where

- \(X\) = Input
- \(W\) = Weight Matrix
- \(b\) = Bias
- \(Y\) = Output

This operation is simply matrix multiplication.

---

## ML Applications

- Linear Regression
- Logistic Regression
- Neural Networks
- CNN
- Transformers
- PCA

---

# Summary

| Concept | Meaning | ML Use |
|----------|----------|---------|
| Scalar | Single value | Learning Rate, Bias |
| Vector | One data sample | Feature Representation |
| Matrix | Collection of vectors | Dataset |
| Matrix Multiplication | Matrix transformation | Neural Networks |

---

# Key Takeaways

- Scalar → Single numerical value.
- Vector → Represents one observation or feature.
- Matrix → Represents an entire dataset.
- Matrix Multiplication → Core computation behind almost every Machine Learning algorithm.

---
---

# Linear Algebra for Machine Learning (Part 2)

# Dot Product

## Definition

The Dot Product (Inner Product) is an operation between two vectors that produces a single scalar value.

It measures how similar or aligned two vectors are.

---

## Mathematical Formula

For two vectors

\[
A =
\begin{bmatrix}
a_1\\
a_2\\
\vdots\\
a_n
\end{bmatrix}
,\qquad
B =
\begin{bmatrix}
b_1\\
b_2\\
\vdots\\
b_n
\end{bmatrix}
\]

The dot product is

\[
A \cdot B = \sum_{i=1}^{n} a_i b_i
\]

or

\[
A \cdot B = a_1b_1+a_2b_2+\cdots+a_nb_n
\]

---

## Example

\[
A=
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
,
B=
\begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
\]

\[
A\cdot B=(1\times4)+(2\times5)+(3\times6)=32
\]

---

## Mathematical Intuition

The dot product measures how much one vector points in the same direction as another.

It can also be written as

\[
A\cdot B=||A||||B||\cos\theta
\]

where

- \(||A||\) = Magnitude of vector A
- \(||B||\) = Magnitude of vector B
- \(\theta\) = Angle between vectors

If

- \(\theta=0^\circ\) → Maximum similarity
- \(\theta=90^\circ\) → No similarity
- \(\theta=180^\circ\) → Opposite direction

---

## ML Applications

- Linear Regression
- Logistic Regression
- Neural Networks
- Cosine Similarity
- Recommendation Systems
- Word Embeddings

---

# Cross Product

## Definition

The Cross Product is an operation between two 3D vectors that produces another vector.

Unlike the dot product, the result is a vector.

---

## Mathematical Formula

For vectors

\[
A=(a_1,a_2,a_3)
\]

\[
B=(b_1,b_2,b_3)
\]

\[
A\times B=
\begin{bmatrix}
a_2b_3-a_3b_2\\
a_3b_1-a_1b_3\\
a_1b_2-a_2b_1
\end{bmatrix}
\]

---

## Example

\[
A=
\begin{bmatrix}
1\\
0\\
0
\end{bmatrix}
,
B=
\begin{bmatrix}
0\\
1\\
0
\end{bmatrix}
\]

\[
A\times B=
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
\]

---

## Mathematical Intuition

The resulting vector is

- Perpendicular to both vectors.
- Magnitude equals the area of the parallelogram formed by the vectors.

---

## ML Applications

Rarely used in traditional ML.

Common in

- Robotics
- Computer Vision
- 3D Graphics
- Autonomous Vehicles

---

# Transpose

## Definition

Transpose converts rows into columns and columns into rows.

---

## Mathematical Representation

If

\[
A=
\begin{bmatrix}
1&2&3\\
4&5&6
\end{bmatrix}
\]

Then

\[
A^T=
\begin{bmatrix}
1&4\\
2&5\\
3&6
\end{bmatrix}
\]

---

## Mathematical Intuition

Transpose changes the orientation of data without changing its values.

Rows become columns.

Columns become rows.

---

## ML Applications

- Matrix Multiplication
- Covariance Matrix
- Linear Regression
- PCA
- Gradient Computation

---

# Determinant

## Definition

The determinant is a scalar value computed from a square matrix.

It indicates whether a matrix is invertible.

---

## Formula (2×2 Matrix)

For

\[
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\]

\[
|A|=ad-bc
\]

---

## Example

\[
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
\]

\[
|A|=(1)(4)-(2)(3)
=-2
\]

---

## Mathematical Intuition

The determinant measures the scaling factor of a transformation.

- Positive → Orientation preserved
- Negative → Orientation flipped
- Zero → Matrix collapses into lower dimensions

---

## Interpretation

| Determinant | Meaning |
|-------------|---------|
| > 0 | Valid transformation |
| < 0 | Reflection occurred |
| = 0 | Matrix has no inverse |

---

## ML Applications

- Matrix Inversion
- PCA
- Gaussian Distribution
- Linear Regression

---

# Rank

## Definition

Rank is the number of linearly independent rows or columns in a matrix.

---

## Mathematical Representation

If

\[
A=
\begin{bmatrix}
1&2\\
2&4
\end{bmatrix}
\]

Row 2 is twice Row 1.

Therefore,

\[
Rank(A)=1
\]

---

## Example

\[
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
\]

Both rows are independent.

\[
Rank(A)=2
\]

---

## Mathematical Intuition

Rank tells us how much unique information exists in the matrix.

Higher rank means

- More independent features
- More information

Lower rank means

- Redundant information
- Duplicate features

---

## ML Applications

- Feature Selection
- Detecting Redundant Features
- PCA
- Dimensionality Reduction
- Data Compression

---

# Summary

| Concept | Meaning | ML Use |
|----------|----------|---------|
| Dot Product | Measures similarity between vectors | Cosine Similarity, Neural Networks |
| Cross Product | Produces a perpendicular vector | Robotics, Computer Vision |
| Transpose | Swaps rows and columns | PCA, Matrix Operations |
| Determinant | Measures matrix scaling and invertibility | Matrix Inversion |
| Rank | Number of independent dimensions | Feature Selection, PCA |

---

# Key Takeaways

- Dot Product measures similarity between vectors.
- Cross Product produces a perpendicular vector in 3D.
- Transpose flips rows and columns.
- Determinant tells whether a matrix is invertible.
- Rank indicates how many independent features exist in the data.

---
---


# Linear Algebra for Machine Learning (Part 3)

# Inverse Matrix

## Definition

The inverse of a matrix is a matrix that reverses the effect of the original matrix.

It is similar to division in normal arithmetic.

If

\[
A^{-1}
\]

is the inverse of matrix \(A\), then

\[
AA^{-1}=A^{-1}A=I
\]

where \(I\) is the Identity Matrix.

---

## Formula (2×2 Matrix)

For

\[
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\]

The inverse is

\[
A^{-1}
=
\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\]

where

\[
ad-bc \neq 0
\]

---

## Mathematical Intuition

The inverse "undoes" a matrix transformation.

Example:

- Addition is reversed by subtraction.
- Multiplication is reversed by division.
- Matrix transformation is reversed by the inverse matrix.

---

## Conditions

A matrix has an inverse only if:

- It is a square matrix.
- Its determinant is not zero.

---

## ML Applications

- Linear Regression (Normal Equation)
- Solving Linear Equations
- Optimization
- Matrix Computations

---

# Eigenvalues

## Definition

An Eigenvalue tells us how much a vector is stretched or compressed after a transformation.

It is represented by

\[
\lambda
\]

---

## Mathematical Formula

\[
Av=\lambda v
\]

where

- \(A\) = Matrix
- \(v\) = Eigenvector
- \(\lambda\) = Eigenvalue

---

## Mathematical Intuition

Imagine stretching a rubber sheet.

Some directions stretch more than others.

The amount of stretching is the **Eigenvalue**.

- Large Eigenvalue → More important direction
- Small Eigenvalue → Less important direction

---

## ML Applications

- Principal Component Analysis (PCA)
- Image Compression
- Spectral Clustering
- Face Recognition

---

# Eigenvectors

## Definition

An Eigenvector is a special vector whose direction remains unchanged after a matrix transformation.

Only its magnitude changes.

---

## Mathematical Formula

\[
Av=\lambda v
\]

---

## Mathematical Intuition

Normally, multiplying a vector by a matrix changes both its length and direction.

For an Eigenvector:

- Direction remains the same.
- Only the length changes.

---

## ML Applications

- PCA
- Feature Extraction
- Data Compression
- Face Recognition

---

# Relationship Between Eigenvalues and Eigenvectors

The equation

\[
Av=\lambda v
\]

means

- \(v\) gives the important direction.
- \(\lambda\) tells how important that direction is.

Together, they identify the principal directions of the data.

---

# Norms

## Definition

A Norm measures the length (magnitude) of a vector.

---

## L1 Norm (Manhattan Norm)

Formula

\[
||x||_1=\sum_{i=1}^{n}|x_i|
\]

Example

\[
[2,-3,5]
\]

\[
||x||_1=2+3+5=10
\]

---

## L2 Norm (Euclidean Norm)

Formula

\[
||x||_2=\sqrt{\sum_{i=1}^{n}x_i^2}
\]

Example

\[
[3,4]
\]

\[
||x||_2=5
\]

---

## Infinity Norm

Formula

\[
||x||_\infty=\max(|x_i|)
\]

Example

\[
[2,-10,5]
\]

\[
||x||_\infty=10
\]

---

## Mathematical Intuition

Norm tells how "large" a vector is.

Different norms measure size in different ways.

---

## ML Applications

- Regularization
- Distance Measurement
- Optimization
- Gradient Descent

---

# Orthogonality

## Definition

Two vectors are orthogonal if they are perpendicular.

Their dot product is zero.

---

## Mathematical Formula

For vectors

\[
A
\]

and

\[
B
\]

If

\[
A\cdot B=0
\]

then

\[
A\perp B
\]

---

## Example

\[
A=
\begin{bmatrix}
1\\
0
\end{bmatrix}
,
B=
\begin{bmatrix}
0\\
1
\end{bmatrix}
\]

\[
A\cdot B=0
\]

Hence, the vectors are orthogonal.

---

## Mathematical Intuition

Orthogonal vectors are completely independent.

Knowing one vector gives no information about the other.

---

## ML Applications

- PCA
- QR Decomposition
- Feature Engineering
- Dimensionality Reduction

---

# Singular Value Decomposition (SVD)

## Definition

Singular Value Decomposition (SVD) is a matrix factorization technique that decomposes any matrix into three simpler matrices.

---

## Mathematical Formula

For any matrix

\[
A
\]

\[
A=U\Sigma V^T
\]

where

- \(U\) = Left Singular Vectors
- \(\Sigma\) = Singular Values
- \(V^T\) = Right Singular Vectors

---

## Mathematical Intuition

Instead of working with one large complex matrix, SVD breaks it into three simpler parts.

It identifies the most important patterns while removing redundant information.

---

## Why is SVD Useful?

SVD helps to:

- Compress data
- Reduce dimensions
- Remove noise
- Find hidden patterns

---

## ML Applications

- Principal Component Analysis (PCA)
- Recommendation Systems (Netflix, Amazon)
- Image Compression
- Natural Language Processing (LSA)
- Noise Reduction

---

# Summary

| Concept | Meaning | ML Applications |
|----------|---------|-----------------|
| Inverse Matrix | Reverses a matrix transformation | Linear Regression, Optimization |
| Eigenvalues | Amount of stretching | PCA, Clustering |
| Eigenvectors | Important directions | PCA, Feature Extraction |
| Norms | Measure vector length | Regularization, Distance Metrics |
| Orthogonality | Perpendicular vectors | PCA, Feature Engineering |
| SVD | Matrix factorization | PCA, Recommendation Systems, Compression |

---

# Key Takeaways

- Inverse Matrix reverses a transformation.
- Eigenvalues measure the importance of directions.
- Eigenvectors represent the principal directions in the data.
- Norms measure the magnitude of vectors.
- Orthogonal vectors are independent and have a dot product of zero.
- SVD decomposes a matrix into simpler components for dimensionality reduction and data compression.

---
---

# Linear Algebra for Machine Learning (Part 4)

# Formula Cheat Sheet

## Scalar

A scalar is a single numerical value.

\[
a = 5
\]

---

## Vector

A vector is an ordered collection of numbers.

\[
x=
\begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_n
\end{bmatrix}
\]

---

## Matrix

A matrix is a collection of vectors.

\[
A=
\begin{bmatrix}
a_{11}&a_{12}\\
a_{21}&a_{22}
\end{bmatrix}
\]

Shape:

\[
m \times n
\]

---

## Matrix Multiplication

If

\[
A_{m\times n}
\]

and

\[
B_{n\times p}
\]

then

\[
C=A\times B
\]

Element formula

\[
c_{ij}=\sum_{k=1}^{n}a_{ik}b_{kj}
\]

---

## Dot Product

\[
A\cdot B=\sum_{i=1}^{n}a_ib_i
\]

Also,

\[
A\cdot B=||A||||B||\cos\theta
\]

---

## Cross Product

\[
A\times B=
\begin{bmatrix}
a_2b_3-a_3b_2\\
a_3b_1-a_1b_3\\
a_1b_2-a_2b_1
\end{bmatrix}
\]

---

## Transpose

\[
(A^T)_{ij}=A_{ji}
\]

---

## Determinant

For

\[
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\]

\[
|A|=ad-bc
\]

---

## Rank

\[
Rank(A)=\text{Number of linearly independent rows or columns}
\]

---

## Inverse Matrix

\[
AA^{-1}=I
\]

For

\[
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\]

\[
A^{-1}
=
\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\]

---

## Eigenvalues & Eigenvectors

\[
Av=\lambda v
\]

where

- \(A\) = Matrix
- \(v\) = Eigenvector
- \(\lambda\) = Eigenvalue

---

## L1 Norm

\[
||x||_1=\sum |x_i|
\]

---

## L2 Norm

\[
||x||_2=\sqrt{\sum x_i^2}
\]

---

## Infinity Norm

\[
||x||_\infty=\max(|x_i|)
\]

---

## Orthogonality

\[
A\cdot B=0
\]

---

## Singular Value Decomposition (SVD)

\[
A=U\Sigma V^T
\]

where

- \(U\) = Left Singular Vectors
- \(\Sigma\) = Singular Values
- \(V^T\) = Right Singular Vectors

---

# NumPy Functions Cheat Sheet

| Concept | NumPy Function |
|----------|---------------|
| Scalar | `a = 5` |
| Vector | `np.array()` |
| Matrix | `np.array()` |
| Matrix Multiplication | `A @ B` or `np.matmul()` |
| Dot Product | `np.dot()` |
| Cross Product | `np.cross()` |
| Transpose | `A.T` |
| Determinant | `np.linalg.det()` |
| Rank | `np.linalg.matrix_rank()` |
| Inverse | `np.linalg.inv()` |
| Eigenvalues | `np.linalg.eig()` |
| Norm | `np.linalg.norm()` |
| SVD | `np.linalg.svd()` |

---

# Where is Each Concept Used?

| Concept | Machine Learning Applications |
|----------|------------------------------|
| Scalar | Learning Rate, Bias, Loss |
| Vector | Feature Representation, Word Embeddings |
| Matrix | Dataset Representation |
| Matrix Multiplication | Neural Networks, Linear Regression |
| Dot Product | Cosine Similarity, Predictions |
| Cross Product | Robotics, Computer Vision |
| Transpose | PCA, Covariance Matrix |
| Determinant | Matrix Inversion |
| Rank | Feature Selection |
| Inverse | Linear Regression (Normal Equation) |
| Eigenvalues | PCA |
| Eigenvectors | PCA, Feature Extraction |
| Norms | Regularization, Distance Metrics |
| Orthogonality | PCA, QR Decomposition |
| SVD | PCA, Recommendation Systems, Image Compression |

---

# Interview Questions

### Q1. What is the difference between a Scalar, Vector, and Matrix?

- Scalar → Single value
- Vector → One-dimensional array
- Matrix → Two-dimensional array

---

### Q2. Why is Matrix Multiplication important in ML?

Because every neural network layer computes

\[
Y=WX+b
\]

---

### Q3. What does the Dot Product measure?

The similarity (alignment) between two vectors.

---

### Q4. When does a matrix have an inverse?

When

- It is square.
- Determinant is not zero.

---

### Q5. What are Eigenvalues and Eigenvectors?

- Eigenvector → Direction that remains unchanged after transformation.
- Eigenvalue → Amount of stretching along that direction.

---

### Q6. Why is SVD important?

It decomposes a matrix into simpler components and is widely used for:

- PCA
- Recommendation Systems
- Image Compression
- NLP

---

# Final Summary

Linear Algebra is the backbone of Machine Learning.

Almost every ML algorithm relies on vectors, matrices, and matrix operations. Understanding these concepts makes it much easier to learn algorithms such as Linear Regression, Logistic Regression, PCA, Neural Networks, CNNs, Transformers, and Recommendation Systems.

In [1]:
import numpy as np

In [4]:
scalar = 10
print("Scalar:", scalar)

Scalar: 10


In [5]:
vector = np.array([2, 4, 6])
print(vector)

[2 4 6]


In [6]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A")
print(A)

print("Matrix B")
print(B)

C = A @ B

print("A x B")
print(C)

Matrix A
[[1 2]
 [3 4]]
Matrix B
[[5 6]
 [7 8]]
A x B
[[19 22]
 [43 50]]


In [8]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

dot = np.dot(v1,v2)

print("Vector 1:",v1)
print("Vector 2:",v2)
print("Dot Product:",dot)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot Product: 32


In [9]:
cross = np.cross(v1,v2)

print("Cross Product")
print(cross)

Cross Product
[-3  6 -3]


In [10]:
print("Original Matrix")
print(A)

print("Transpose")
print(A.T)

Original Matrix
[[1 2]
 [3 4]]
Transpose
[[1 3]
 [2 4]]


In [11]:
det = np.linalg.det(A)

print("Determinant =",det)

Determinant = -2.0000000000000004


In [12]:
rank = np.linalg.matrix_rank(A)

print("Rank =",rank)

Rank = 2


In [13]:
inverse = np.linalg.inv(A)
print(inverse)

print("\nCheck A x A^-1")
print(A @ inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]

Check A x A^-1
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [15]:
eigen_values,eigen_vectors = np.linalg.eig(A)

print("Eigenvalues")
print(eigen_values)

print("\nEigenvectors")
print(eigen_vectors)

Eigenvalues
[-0.37228132  5.37228132]

Eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
print("Vector =",v1)

print("L2 Norm =",np.linalg.norm(v1))
print("L1 Norm =",np.linalg.norm(v1,ord=1))

print("Infinity Norm =",np.linalg.norm(v1,ord=np.inf))

Vector = [1 2 3]
L2 Norm = 3.7416573867739413
L1 Norm = 6.0
Infinity Norm = 3.0


In [17]:
x = np.array([1,0])
y = np.array([0,1])

dot = np.dot(x,y)

print("Vector x =",x)
print("Vector y =",y)

print("Dot Product =",dot)

if dot==0:
    print("Vectors are Orthogonal")
else:
    print("Vectors are NOT Orthogonal")

Vector x = [1 0]
Vector y = [0 1]
Dot Product = 0
Vectors are Orthogonal


In [18]:
M = np.array([
    [3,1],
    [1,3]
])

U,S,VT = np.linalg.svd(M)

print("Matrix")
print(M)

print("\nU Matrix")
print(U)

print("\nSingular Values")
print(S)

print("\nV Transpose")
print(VT)

Matrix
[[3 1]
 [1 3]]

U Matrix
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular Values
[4. 2.]

V Transpose
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [19]:
X = np.array([
    [20,170,65],
    [22,175,70],
    [25,180,75]
])

print("Dataset")
print(X)

print("\nTranspose")
print(X.T)

print("\nFeature Means")
print(np.mean(X,axis=0))

print("\nFeature Standard Deviation")
print(np.std(X,axis=0))

print("\nCovariance Matrix")
cov = np.cov(X.T)
print(cov)

print("\nEigenvalues of Covariance Matrix")
values,vectors = np.linalg.eig(cov)
print(values)

print("\nEigenvectors")
print(vectors)

print("\nPrincipal Direction (Largest Eigenvalue)")
print(vectors[:,np.argmax(values)])

Dataset
[[ 20 170  65]
 [ 22 175  70]
 [ 25 180  75]]

Transpose
[[ 20  22  25]
 [170 175 180]
 [ 65  70  75]]

Feature Means
[ 22.33333333 175.          70.        ]

Feature Standard Deviation
[2.05480467 4.0824829  4.0824829 ]

Covariance Matrix
[[ 6.33333333 12.5        12.5       ]
 [12.5        25.         25.        ]
 [12.5        25.         25.        ]]

Eigenvalues of Covariance Matrix
[ 0.07406187 56.25927147  0.        ]

Eigenvectors
[[-0.94265357  0.33377276  0.        ]
 [ 0.23601298  0.66655673 -0.70710678]
 [ 0.23601298  0.66655673  0.70710678]]

Principal Direction (Largest Eigenvalue)
[0.33377276 0.66655673 0.66655673]
